---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: propmon-secret
  namespace: default
spec:
  encryptedData:
    eth-rpc: AgBYMl+/NA9qScSz1jsaTAYMwmY6yFbBmli2UxbOcMQftUGn2lROLJxWtLyECKJ12VlaXUjw6rawoTAQ8x3Qjp3XDl4SMYH1Lg8C+l5QTaqj1P/zIfERLudgeeHVe+/gZ0ozPiN6FHFDFxgCRSpriasSBF+7dZci42i9SGeni0nYVQP/aLsMPHrJBqM/6G0qPUIvcFXm9Fvq4mgbOuAs9Y67t8huTCVadB/gbxHkxsRDvaSBhCVEkHQV5aXNCgquWVX6mhmt8q2+iQJuNwmPLl88ym4sx0apAxKMsSJhwRAK1mqCFgkFyYcdmzH0U1d0+ulvk9D0jC/Jx/7f4+phxoK/SdBaNbqhYULgDhGxaQXIrjEea4t7erNNqXoWHdnv1fk1yoK6Z5nxz7REmbs7a5AZ94JlDljJ/WeuSH+uqtEVlBvqjCmhCtmU/67g+vXsEvi2FAHhuHNSOmiLLlQ4w5fQ/zgYHJWoL9jCvp1gP0eoV08o1eEYdAyuTvf4x/XVAC/cexjVEr1nVJ6uoNpkQ99ef3f5jTgucv0uIhFtO4q2qTJfjblWhzqRAWYORxmSQBtnSsSDrNVdymHOqNKjxUz7wg7khpR0nw7rnjhgKK/LptzFKLajEjGytap3yF5GCwAGLBMvIpY4ogOn5npUEpnSecMiSpP/V8U5U9gHp8rtia8YL9nJlbFzWo/5vF+F3IMSABarLk8xXy2xpy86ywC+taVVnOuaF+mNgYu9uQ9KlJIG1iwYdbAUXiyuNEATRMhf17QWlXLAobHRTplHDadJz4m9j8Tt
    private-key: AgBml1eKG1ZgIzkb6Qwav6yD+UgvrmCQoFffGMqNm12iwS+C1LoqXPZ7HmdNaJRHXikjm1xauUlIyGhRf44rAoBD6PonP7kI5WqAZ91MW5hxkonD5IJmZpl8xoWionGQNu7WFqVrMXrpN36DMaUdLEUb4K1np/IKro0w5f8GsJk6Mk+zczFTfFe4ScrdF/ZT9YF7pqtrqqvNf8KMFB7VZ3KhitMj1GwV9DjKF6fAbGXBGiEuwSvCi8kCYsP869yqQEet76KCz34qbKkJZ7CojntlYq+zuXvd4KlQRKx3FMWtb+Qb544o476V6QWSsPo4I6vF+qYV7x58rcnMn/mmU3mJ/OIEwzKw5f44pYd93V3IefWaMtTc3P9y/GxwtSXN6jCoy+663J8czxFMuDZFYDiYsmlHPpotVxVa+OknHFI1qFcDc4GfNu6OPSEys1ZP9ORSTmm+CmO/lA/Gvc7UloftsDdnGCtvEjJy3XJRkG7hGqAoOTEeIFNtmi0ZCOZnnhQYuoOZm2LbktSVjGbF7UrLTTWDsbFFntna/cSmqZnpdyTGjxZs9oDu3o4EpgEIQkiGLElyDgtu9GlCDf/4oj1z0fWC9GkGGLmn94XGbu40J01LhrHGALTwam11642vAmnwKivm5CZxe7SSIGGHuiej3PpBVPFNQox+vLSV04B8sVYmA46fsrG+QJsfHcWT7DUWZlQRl1adOzRB5YLP9EV0Z41kRTKC0uDCPzYZP55HYKu/9nW4FkzRTpMKi2OpFMJDGvSWi2LS0cM0wmzVyM7HaQ+/
  template:
    metadata:
      creationTimestamp: null
      name: propmon-secret
      namespace: default
