apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube101-raw
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/godzillaba/argocd-testing
        revision: use-helm
        directories:
          - path: raw/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/godzillaba/argocd-testing
        targetRevision: use-helm
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
