apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube101-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/godzillaba/argocd-testing
        revision: use-helm
        directories:
          - path: helm/*/instances/*
  template:
    metadata:
      name: 'helm-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/godzillaba/argocd-testing
        targetRevision: use-helm
        path: '{{path | regexReplaceAll "/instances/.*" "/chart" }}'
        helm:
          valueFiles:
            - '{{path}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
