apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fund-distribution
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/godzillaba/argocd-testing
        revision: use-helm
        directories:
          - path: helm/fund-distribution/instances/*
  template:
    metadata:
      name: 'fund-distribution-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/godzillaba/argocd-testing
        targetRevision: use-helm
        path: 'helm/fund-distribution/chart'
        helm:
          valueFiles:
            - '../instances/{{path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
