---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dummy-secret
  namespace: default
spec:
  encryptedData:
    secret-key: AgDOFsaaJvKjfl9jTKDULrqKoQFQ9i0HB/7vrD4AGOFIAmPPgOQnKDGKHhm6esevAFdixgj9TLMp4rVI+fa41H8aPyoXf0e8wKhBZkSZWOf7EU0KF7Ta4VmwYbvV5INlQsKLIyX9e7F3UkTUV8YoirGu2RrloIdWVZoZbB2/L08nFr0axH59/lSRPhtE1I3MeN7ghj0qnzDZ4BZ2ecR7Mga1FYJUQNQpFz6oyiO38+/zYjS4CGkyOd5vB32WyCaprh/ztb4PaaKyY7FgXx6bHPqpwCf29l62omv5lrcn+3erhQsdmIIDRBl4CwTcHONa05thtQOD90hZJkem0FgVKubEHbSjH++xsy4cgzhVP5kJeUcF+jNw9hMUoauOD+HCBEG/Jv7PMsUFPjiMTeusJMx3DWNW+dEFjM1vrnjUg3auvcBoIm+DTzxvJAO8SND/4llgkisup/+EBY95SuzC2bNFbjk0OUowSuWPx23/hxStyt7byoZNcXRIoQSvvYciOXEpLXb7jala47goNzNbgMMHrfFoUNkpOw82FFLhD1EA/Em+GgvU0xHvXFrCftgEWYJs/ob5JoCYOexzZfPttQox2Q8Dp5ft1LQZb+T1ZLDJuQhDxfAQ1rCirpbHZNi6OdeKJR1w8glr4MD3ILP+UA7UZiQ7IkJcnPBZnr68I/QdqAWmGxRtpTJ72ZIF19wrMQvTvWN1YZ0eWGPIxy3p8ou/9t+YwxRTvUgnvrYrajwdt9st1VF90cM/UAO0/eNZ1EEaUCrHpfTpO3GR4GJzLThSGTc6
  template:
    metadata:
      creationTimestamp: null
      name: dummy-secret
      namespace: default
