---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dummy-secret
  namespace: default
spec:
  encryptedData:
    secret-key: AgDHRyY98cNpY93JCIr7ySAkxAKGCTlAGNujxpuIC9gjGLLE6lZGj2UfjNB7HWy7ltc/jLdwQ/CPFV/yplBDbBn5u4d1zOh4DtpwO5TJ8YoAUQMEBAmr4sn+TIrU96aFYxOQFgx+bTJ1yPTYrx9+G8d8C2A/WQvz7T1QhH/+eAnFM5naoFDqtWgUMIQDiFnwlvT4dQc46/AkUwDjQgigwkV8y+12AGZHZtfFf159o51zUc4go3GYjQtGlAUgB8t4udgQOX00WhofzJYk/nQIOH3iznG/SCBuZiFXoIuhHTV8mnbKt6OTX0h59SJIEdVYAV7I2PyC1HjzLJu1tuH0JwSHNdPKE9dG8OTXyy76UR+Xv4LF1bVERapsH0oCrolZpLIGuahy9cg89rtwZzCI7mAn3DcjN4UCxqiBaEhqJFSTs3rCp6PmQgYmzLSalDalBR14h1yvUXDBpYATR6k9sqxKDLV+lal3actGP6FAp3ypVUMa8Wuwm1jTBaS55qVZAmPBQXDyPr/nR4VDTeVoKHMxAJ1Yj3CvxDaVooVs+ZPLgkHkfHLff3eLKS+tGF3syD6pMjrfOE30Fh8AqCWaJgpD/0VOvNDutYSYBBcxRwX+HOdkLk7dvCH+KDT8L2axsKU6Rch0rT52ybIbHfs+CN4JrUOLuZEMxyPloQ1YpgcvFFtT6hm7GLasWzMLCtlCYQrONHP8wDcynCigDjKV4WW1CP+DGHA14ycBJQM2BXew2W7L34j6LqorxpaALxWHsAZqUimlJwhiJE41Pwlkch4FceAG
  template:
    metadata:
      creationTimestamp: null
      name: dummy-secret
      namespace: default
