---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: propmon-secret
  namespace: default
spec:
  encryptedData:
    devnet-private-key: AgCsnv3eJXSjrc3V8lKvqI3a3AbKeeY2fpYGYz4xAIOkMsmR4/nfFvrDlYCvtweTHWzPEKqnrH7OcFj2vVHawA4GtF2oAIZd6KfadWkzDrj1hTB2u7hXK8t9DZJqI6FdoFU/BRrRevKXImuAvewaShXooXj+1Prn5r1aImm6DQ5Rm3bQIqkS+S+dWtS8WMBWofQ9eFgh3oNCgt5NzCpLQcJptUMaeGhLHhnJoGbiPQhagtYfb826woYyrtgxxzVLvLf3eccADku7PXP28P9BmKPVW3rQtNEp1KUSSmf5Tvow4qPdVn84SSF9QRdmTgXuTQHTgV4JbB0rUATxeQFExKd/Qwc7sSlGV4b9DXShq5wXvYjcMkGh6js83fcmGqRECqj74HZxuV7UYC7YEPs0EVf2WakXpCMNZbAVChKF2KSpqk8cfOWPktgDu8+fXmIY+9ifayBzZnBc27p/iNwM9REdUhjtRoTT6zyKg3nhadOw0Nc1UM/I3IczoL5rNEBidBW4uaFQuWJW/TFqmyEgOXq5sKQ7JZiOa6R1r6GsBfjO+FrR8y8ac+o7pPGD+NFBjGlG8haAg994gVqLnwOTFp5hdNl6MuTZNK164IPrWPYteCorv91R4VsDvOdm8jfwAQVn71O89n4tupF2So68qlU0tTRsBWkt3Ze/UmcIXin1K5IaOYjpLrqS/JM0rCZ5jH1gFBlH0ql/JTPDpLlQG4oRq71AjugogUVF7uxBaozIrZaZq5PlWyE+K9+3bDo5QnTp3pLc1O+x6W1FS2WNKfvtnzw=
    private-key: AgBcJUOuQ2KxR+GK464zpwJ83tXuh7LA1P28HnwKH3jawpHdqqf8Dwe+IgZVLh9Mr+szFljtnhMVR1BAVd40eN3bkGceQgmBKMWOC84hFXVfGIdZoD2dc37ILsQlpdvAgqmao8GVVIF0deVc5q0tlrNc/Ff4WJS/fflTDX8awihEEG7VvH8D9rHOHXQgC0FjjeWvKj4zqkDv7BH8j4I/sQxG71MZY/gNhHcH13S0KytIOUOy4zAzE6c0Eey8ZiTtzVl3SOwr6NyZJ/h5X9rLrYWcW6HV2BWvecFgET49glfBhNnMB8zgvlHDDB8SuIPXBTxYizJfRsxScGEtZvUvhK6bedAVk4ETQ3JYfSfoZU5BhP4TJoUfLHdJACuwMlYRk/HinLIfFC0tx/YhMe2HPLGnM+1iKkZnSs+Q6mFe6366soW6aPun2ruYpkLt0PF4FAEZ6FXorDG9D6sQmhr0YSRY6CYvxhersrAHLVwywmFNKbO1CFEknC2I1Z2S07GZuY1uni05d2h/Oj4IWU6G1ugWi1WAIOEo7Z7+hYsvMmpxvrOuXESjbBeb3XNCX/dYsZbz198adF1mGXtuGB3SnkR7O5TK6HOgTRFaUQcvD2WTFlVTFVUJh42kxmvFiurob4FqGdec+wZAHjt99UCD+qczsIjUNFVMH8hMkkZKWxB7tGifIpX26d+iQyT+mgCRxbgt9bHn8pyR8OmLOzCBNv4Le5kNh67OpEwr1WgWx/TWKE5e4Oa2D6YSNn43Nd+3B5Qz89xv30bsIDxD7NOZisMi1yw=
  template:
    metadata:
      creationTimestamp: null
      name: propmon-secret
      namespace: default
