---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flush-timeboost-secret
  namespace: default
spec:
  encryptedData:
    devnet-private-key: AgCHvf3rYZVa7Bt8UpT314w1S0gOjSX1atqVb8E5LPjWJzns8TwTMj8pCyYGNnmfD/nHarlYCrBtWFiyFhSQKl9Eoyfe7+Nd6F0xS5TfSHLNzsbbvjl0JtiClgcOzElxp/nZKZCt/5xf4WmdixRc+1cQimAqZVEX9eCjkiYCgRssPKnawuzITjA5S4vJ7zkpgeEbztpMkzwA8lwgojsTzvDVdSwz5zTcyhTUCegLbEGrvvtHMWCHa6uvSN3bD7c4FzqeBF0EoPcoaEmgnSZoG/Neu10PLHJ5IPh4jq9c8M4b0t+LcLi3Yy+ZvDmatpcuH/e0SEtVCM99l9i3dl/CYaQ9VrOCfWm4hUj+FmDWSvQ/5lBsHjVNTkezfScNQt20i7wQDRNCrvKWWBRyT5RcQsVTCbgulovNRvjm/xrPhlmwkLDgHKOlcNMWi3wUfHSq9KKYJTIC2mSghLXhsue0aSwjVxkG8klESgtnRomyvJsaMG+a3my7XCoTOe6GRvohPOJRQw5b5L+z5ttL9f3AqqTJwf3HXnd90wugON7iFHDe99rbKpQ37fIKmpc1cAQV2Ib7J7xbgnIFPg5AWdkb7TmbxrUasN1JzZgNW04Sp6EU6uYc22msrY3bhhOYN1u0CRRkw2iSj7LN0mn3zo1q/DAg9rw31Q7BKpxo6gJT121HzgX4FpZGRW1UXPcQMoISVmtZrl8fOZMxcPwwCTd5Dspzxc2mWMndsopBQHZgu7bSQ/LDBPM0TamhNtkmCPkZwuRP0LmxqlmegDBkOgJpiAXGudw=
    private-key: AgBrcJ0VK/rDfUKbNi5NGCNKYyAH6OoVfejYktX0b+N3rk8+LND+GTu2ZvReBD/0z3gcza5qj4ukFOvOI7MMkKKXAPfNcVH1Cowo1Hmc9xQftxymKFEmcBMfR7qsu/9U9m5wHVptdjtr2+0c/4pJW5VOsZklgq1JLvQg3mlpXpMdyqfIMCXUJcrNo+Ylu4eoQ5Y9KhJivDGoMJJRdBZLqxladIfXAa24bM8xhU4f55yeKUrDO3yPX0LDI+J9SRtpnG54NYEX9r0irhLDu9HkPqWF7qZnwY5vkOMuEbALiJA0JhnEnhOqAEzdO8Yj9/eLcZkLY6bx1YHn7KYs+GkDo4iPwUfJ6Yj/EbuQYKwTOaSsGbbiuv8A1/b5VkXRzwD8a2zzTHbhrSCUGES25BCBoK6x+uoHz83oOa9VVIW5Bu99ZYXYKEKVMyEQ6ZMTQkpz5T+8NKkQtOGA76ukupmN10AOLKpkpA5/Z1a2zXXitrm9T2zRbDByvmO3ia6cXNNaOoKF+V6ILjDekvwz2j20LpzKL005lKY9EwKPuDzqhPoQipQMiSNDn+1PehE3Jy/oqDw9nEpoJgPYECI08ZoB5kVxmPt+Lpm+aajktdMw1u1jGGswyguxhfVmeN7UZNykFFKZ9ldhydDAxhqeliZzs1xJ9YAg5v99yCOineW/U+cFVJYBWPH1u8fc7TcL/i9iX9vbUgu4oVcAN+IADz6rTdumoyHGuIKbvWibaogFn47CuM5AKhUWvECqwZK/aAtsZbdfeYgVUC/DosKXdlPnwtWEkek=
  template:
    metadata:
      creationTimestamp: null
      name: flush-timeboost-secret
      namespace: default
