---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: propmon-secret
  namespace: default
spec:
  encryptedData:
    eth-rpc: AgB8wzxw0bdde/JL8r9+BuXsw+e1n+oq/SDE9B7euutEwRKipDHpKtn8jK1G/pzkfsG/2LoXMbnLoIgK6m8ogDCXfdayARqdkrXpif1w2aBMcObNcbAm30zAsUfl5spb6RYvWDmELont8JPqFcrrxYK9/+zeM3qADZk6Vl78jxr6K43+Co+zfiF3BTUI97HcYZkzvMU+5Pi2GqfbuxT2GBkqmy38ZKw8SZxhGkEmx0srlTvAzMipKvlr8sLa64zbIi7QjBGa1iUX1rWCXl3qCJnB5YvUGMLFCZppkOjRq1mc91kYFS5WoGLT1QNhTv+BS6WHKmeshpCCRDKkbsMhTx7hVq49FBnZwB97AVJLTHHL8kv9bsAi+HR7bGWPvhfyhD9OqLmcEbV2eZcsS+Gsxz/4cnvtm1Loks6zrC8DPy3jCfZVj1Mh/sVXAnKIhRFDwyigS44lYQEoYYcvoeKW+XsLMDmhkut67tU3+2MrugOnlgjtmDuksIeKIdb1rhYZk7oq/IjsdXgAPQXTfgkgdqqAx1DIWspV/ZpITo4v1HMs7zb3lzNjWChTDghve+7U1zy0HgHq983a4VAkgwGlBffsFHpoFqf47Q3UK9N9OpCXBZw3kC1JL0lZryZiIo5e/83psaDU9SPgRxpGaLTU2lVlad5G+Ha534VHkoL+bhRZcyhHg51JQgTaB5oQfzBHCjYvbojYaCWvdgC0JqT80bayPXThPW/KZTj4MvEKgWI5EQTCc8vYWlBO1asNlCATZ3/8hdh7SB3tmGffllAf4FdcNKODvFZS
    private-key: AgBRx/aMlOx7k1xOMSC0ZtKC6GiinVWWmbdUW1/Mh5Mfk/RywFFyLZ3uVtpiOg+EzpOI1XynhEdyXxKrjndkdHXYV8e51YLZvYHnsuegiz1Sd1SAwdGRXZPZsWFdbhy6T2etLrPGdhVkbmsvTFk1L/X5MZlUr3YlFLJSAyAhakmsBH3Q3BfRNk0Y3YFK7Ets7/SAo5h6LCgGN/34tlQTbdOPlVTL195sttrzkhUtGMj4Co9uZYXFvag1ZFm4i+/gSykbAJ/DXBU38LRsmN938WpoIAQJYEYYQICDblmw4vaqcqs+qTfM4izX3+1Vza6tvJfAAuITq4ePu2uLV/o3AB1AcyNAkHrpj9NUGBAj9QjcBviddsRFDmibMCYVOjsJ8heDNsQa/jOvxWNUHdz2ZZCfEip6BQGSGAcZmYG7Thn+TZp1xgkuawJZmMCjwfc0Qq6cvuaEIUEqJvWRo9ZzsFMMM8GFZWUQznVY682+PvSvP1FyNnccRWYgx8eEPIXHZ43nFe3ZvcpQ7MqUoJPcwqXMAD1LvQMAo6XhEF8jRAK7JZnRumeJQVeQvnMwtiik7fHSUOyWU1lBe+9iSMIQnNpwoeyQdZrRKJYhc/39rfOTINsBGl73bN/YvQ/jdr10O5JlwPkUPh+AIoVj2e9a0ktTWNSGEQCZvR3KLEM0e8mLDxhttRlJLr72Sk9wg+YX3+k6uF791ih7jG7DCZQTSZRNZAdA3C7vQSHf2Gk0huoL+Z8NjFiYOl+SZFFprLgU/sKJ6GwUCt2qB5ebTO6RFdTmF31N
  template:
    metadata:
      creationTimestamp: null
      name: propmon-secret
      namespace: default
