apiVersion: apps/v1
kind: Deployment
metadata:
  name: long-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: long-script
  template:
    metadata:
      labels:
        app: long-script
    spec:
      containers:
      - name: long-script
        image: long-script:latest
        imagePullPolicy: Never
        env:
        - name: ENV1
          value: "env1_value"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: dummy-secret
              key: secret-key
        args: [ "--foo", "bar" ]

