apiVersion: batch/v1
kind: CronJob
metadata:
  name: "job-{{ .Values.name }}"
spec:
  schedule: "{{ .Values.schedule }}" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fee-router
              image: fund-distribution-scripts:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: CHILD_CHAIN_PK
                  valueFrom:
                    secretKeyRef:
                      name: fee-router-secret
                      key: private-key
                - name: PARENT_CHAIN_PK
                  valueFrom:
                    secretKeyRef:
                      name: fee-router-secret
                      key: private-key
                - name: PARENT_RPC_URL
                  valueFrom:
                    secretKeyRef:
                      name: fee-router-secret
                      key: "{{ .Values.parent_chain_name }}-url"
                - name: CHILD_RPC_URL
                  valueFrom:
                    secretKeyRef:
                      name: fee-router-secret
                      key: "{{ .Values.child_chain_name }}-url"
              command:
                - /bin/sh
                - -c
              args:
                - >
                  yarn {{ .Values.subcommand }} \
                  --parentRPCUrl "$PARENT_RPC_URL" \
                  --childRPCUrl "$CHILD_RPC_URL" \
                  --ETHorTokenAddress ETH \
                  {{- if .Values.parent_to_child_reward_router_address }}
                  --parentToChildRewardRouterAddr "{{ .Values.parent_to_child_reward_router_address }}" \
                  {{- end }}
                  {{- if .Values.child_to_parent_reward_router_address }}
                  --childToParentRewardRouterAddr "{{ .Values.child_to_parent_reward_router_address }}" \
                  {{- end }}

          restartPolicy: Never
