apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-script
spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-script
        spec:
          restartPolicy: OnFailure  # Good default for cron jobs
          containers:
            - name: periodic-script
              image: periodic-script:latest
              imagePullPolicy: Never
