apiVersion: apps/v1
kind: Deployment
metadata:
  name: periodic-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: periodic-script
  template:
    metadata:
      labels:
        app: periodic-script
    spec:
      containers:
      - name: periodic-script
        image: periodic-script:latest
        imagePullPolicy: Never
