FROM node:22

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.foundry/bin:${PATH}"
RUN curl -L https://foundry.paradigm.xyz | bash
RUN foundryup

WORKDIR /app

RUN git clone https://github.com/OffchainLabs/block-hash-pusher.git .
RUN git checkout 085872efb820563b9c50d85732457147523fbe67
RUN yarn
RUN yarn build
RUN cp .env.example .env

ENTRYPOINT ["yarn", "run:push"]