apiVersion: batch/v1
kind: CronJob
metadata:
  name: "job-{{ .Values.child_chain_name }}"
spec:
  schedule: "{{ .Values.schedule }}" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: block-hash-pusher
              image: block-hash-pusher:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: PARENT_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: block-hash-pusher-secret
                      key: "{{ .Values.parent-chain-name }}-private-key"
                - name: CHILD_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: block-hash-pusher-secret
                      key: "{{ .Values.child-chain-name }}-private-key"
                - name: PARENT_RPC_URL
                  valueFrom:
                    secretKeyRef:
                      name: block-hash-pusher-secret
                      key: "{{ .Values.parent-chain-name }}-url"
                - name: CHILD_RPC_URL
                  valueFrom:
                    secretKeyRef:
                      name: block-hash-pusher-secret
                      key: "{{ .Values.child-chain-name }}-url"
              args:
                - "{{ .Values.inbox }}"
                - "--num-blocks {{ .Values.num-blocks }}"
                - "--min-elapsed {{ .Values.min-elapsed }}"
                
          restartPolicy: Never
